AddTextEntry("WEAPON_AK47U", "AK-47U")
AddTextEntry("WEAPON_AK47", "AK74")
AddTextEntry("WEAPON_wirebat", "Barbed Wire Bat")
AddTextEntry("WEAPON_BARRET50", "Barrett .50 Cal")
AddTextEntry("WEAPON_Bayonet", "Bayonet")
AddTextEntry("WEAPON_Fireaxe", "Fireaxe")
AddTextEntry("WEAPON_GLOCK17", "Glock 17")
AddTextEntry("WEAPON_HK416", "HK-416")
AddTextEntry("WEAPON_katana", "Katana")
AddTextEntry("WEAPON_M1911", "M1911")
AddTextEntry("WEAPON_M9", "M9A3")
AddTextEntry("WEAPON_MAC11", "MAC-11")
AddTextEntry("WEAPON_CJ", "Colt Junior")
AddTextEntry("WEAPON_MCX", "MCX")
AddTextEntry("WEAPON_MP5", "MP5")
AddTextEntry("WEAPON_P99QNL", "Walther P99QNL")
AddTextEntry("WEAPON_REMINGTON870", "Remington 870")
AddTextEntry("WEAPON_SKORP", "Skorpion Vz. 61")
AddTextEntry("WEAPON_smithwesson", "Smith & Wesson")
AddTextEntry("WEAPON_SPAS12", "SPAS-12")
AddTextEntry("WEAPON_Tri-dagger", "Tri-dagger")
AddTextEntry("WEAPON_ump45", "UMP-45")
AddTextEntry("WEAPON_spas12", "SPAS12")